### ISSUE TITLE
Use OEDT for incremental builds

### ISSUE THREAD

**Issue by lievencardoen** [omecra/de.omecra.oedt.updatesite#109]
Hi Lars,

This is more a question than an issue. 

I was wondering if we could use OEDT to do incremental builds with Jenkins? We have thousands of sources and our builds take 2 to 3 hours. Each time there's a change in the sources we compile all sources. Problem is that you can't just compile the Git Diff. If an include file is changed, you also need to compile the sources using that include. With classes probably same thing.

Would there be a way to use OEDT? I'm searching for the same logic OEDT does in eclipse. If sources are changed, OEDT picks them up, checks its internal database, and compiles the necessary sources.

Kind regards, Lieven Cardoen

**Comment by lneumeier** [comment]
Hello Lieven,

Running OEDT without an eclipse context is not possible, because OEDT's incremental compile highly depends on the API of the eclipse framework. 
Another problem is the evaluation of preprocessor blocks in OEDT which might lead to false/positive compiles, which i think is fine on a developer machine, but might not be okay in build process for production purpose.

One solution that comes to my mind is using pct (https://github.com/Riverside-Software/pct), which supports incremental compilation by analyzing XREF.

Another solution would be writing the evaluation by yourself. 

1. Compile all sources with XREF
2. Analyze XREF and store the important information in a database or somewhere else
3. Compile git diff with XREF
4. Compute references with the information from step 2
5. Compile references

Step 1 and 2 are only needed for initialization. Step 4 should update the information.

**Comment by lievencardoen** [comment]
Thx!
