### ISSUE TITLE
REPOSITION-BACKWARDS not recognized as keyword

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#125]
While REPOSITION-BACKWARD is recognized and colored, REPOSITION-BACKWARDS isn't.
In the default OpenEdge editor this keyword is recognized/colored as expected.
Sonar seems to flag REPOSITION-BACKWARD as an abbreviation, while the OpenEdge documentation consistently uses REPOSITION-BACKWARD...

**Comment by lneumeier** [comment]
I think that this is a false/positive in Sonar. PDSOE colors REPOSITION-BACKWARDS and I can add this to OEDT, but documentation and code assist in PDSOE only show REPOSITION-BACKWARD.

Because of the documentation, I would like not to change REPOSITION-BACKWARD as an abbreviation for REPOSITION-BACKWARDS.
