### ISSUE TITLE
"./" interpreted as "//" by editor

### ISSUE THREAD

**Issue by RobertHeintzCH** [omecra/de.omecra.oedt.updatesite#144]
Probably not used a lot in productive code, but weird anyway.

RUN ./xyz.p.    is colored like  RUN  //xyz.p.
RUN ../xyz.p.   is colored like  RUN  .//xyz.p.

It compiles correctly, just doesnt show it as normal code like the default OpenEdge ABL editor.

**Comment by lneumeier** [comment]
`./` is an undocumented old syntax for single line comment. I look into it.

**Comment by mikefechner** [comment]
A period followed by any non-whitespace character at the beginning of a line - when outside of a statement is treated like a single line comment.

`     .this is a comment`

while 

`    . this is not a comment `

due to the space after the period.

Ugly, don't encourage anyone to use this syntax. But it's not just ./ that is treated like a line comment.

**Comment by lneumeier** [comment]
Fixed in 9.4.4.
