### ISSUE TITLE
enhancement request: Compile on save should compile file during build

### ISSUE THREAD

**Issue by cverbiest** [omecra/de.omecra.oedt.updatesite#73]
* "Build automatically" is on
* "Compile on save if auto-build is disabled" is on
* a build for a changed include is running (+/- 400 files)
* editing another source, no include, a .p

On save the .p is not compiled, it will probably be compiled after the current build for the changed include is finished.

It would be nice if the compile on save would have a higher priority than the compile triggered by the changed include.

An explicit compile works.

**Comment by lneumeier** [comment]
Compile on Save uses the project builder to compute all dependencies and then compile the file and all dependencies. Each compilation process triggered by the project builder is running a "workspace job". Multiple workspace jobs for the same project are executed after another (this is done by the eclipse framework).
An explicit compile works, because this is calling the progress runtime directly and is not going through the project builder.
