### ISSUE TITLE
Correct using statement does scan for include files

### ISSUE THREAD

**Issue by Ton-Pe** [omecra/de.omecra.oedt.updatesite#77]
Use case: we have a internal procedure that is in include file. That procedure defines a variable for class instance. (Well, this is not very good coding practice but still).

test.p
`BLOCK-LEVEL ON ERROR UNDO, THROW.`
`{test.i}`

test.i
`PROCEDURE foo:`
`    DEFINE VARIABLE xResponse AS WebResponse NO-UNDO.`
`END.`

First problem is that when I define that variable USING Statement is not added automatically. Well, this is understandable because USING statement must be first executable statement and  editor might not know what is the parent program from where the include file is used.

But bigger problem is that when I add the USING statement manually to *test.p* and save it, the using statement will be removed from test.p. So it seems that correct using statements function does not read from the include files. Native ABL editor does not remove the using statement in this case. Is it possible to fix this?

OEDT version is 9.2.1. OE 11.7.4

**Comment by lneumeier** [comment]
> First problem is that when I define that variable USING Statement is not added automatically. Well, this is understandable because USING statement must be first executable statement and editor might not know what is the parent program from where the include file is used.

Because of these restrictions, the Content Assist (CTRL+Space) inserts the fully qualified name of the class and ignores the using preferences.

> But bigger problem is that when I add the USING statement manually to _test.p_ and save it, the using statement will be removed from test.p. So it seems that correct using statements function does not read from the include files. Native ABL editor does not remove the using statement in this case. Is it possible to fix this?

Include files should be as independent as possible. If an include can only be used, if the last parent (consider include chains) contains a using statement, it creates responsibilities outside of the include. With fully qualified names, this can be avoided.
The correct using action can be configured as a save action. Parsing and analyzing all include chains to evaluate a using statement regarding include usage will impact the performance of this action. This won't be implemented in the near future.

**Comment by Ton-Pe** [comment]
I understand that. Thank you for your comment.
