### ISSUE TITLE
Correct keywords - false positives

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#90]
Hi,

Using the "Correct keywords" functionality, a lot of false positives can be observed.
The following is a short list I observed:
- Properties of Progress.Data.BindingSource that coincide with Progress keywords get upper cased, while they shouldn't (HANDLE, POSITION, REFRESH())
- System.EventArgs:Empty becomes EMPTY
- CATCH myError AS Error (with Progress.Lang.Error in USING statements) becomes: CATCH myError AS ERROR

Regards,
Lieven

**Comment by Ton-Pe** [comment]
Hi,

I would add also word 'item' to that list. We have a table called item and every time I write the name of the table it is capitalized automatically. So trying to write 'FOR EACH Item WHERE Item.ItemCode =...' it becomes 'FOR EACH ITEM WHERE ITEM.ItemCode = ... '

**Comment by lneumeier** [comment]
@Ton-Pe 

The preference "Use smart keyword casing while typing" (Window -> Preferences -> Oedt -> Editor -> Keywords) should fix your issue. Is this enabled?

@LievenDeFoor 

Yes, this command is not context aware.

**Comment by Ton-Pe** [comment]
@lneumeier 
Enabling that setting will fix that issue, thanks. But there is a downside. If I enable this, then the property keyword (ie. when defining a new property for a class) is not capitalized (caused by a database table named Property). That's why we have this setting disabled. 

Well, we need to decide which one is more distracting. Probably will enable this setting. Of course it would be nice to have this fixed, but I totally understand it might be difficult.

Thank you for your answer!

**Comment by lneumeier** [comment]
@Ton-Pe 

With OEDT 9.3.2 your problem should be solved (PROPERTY).

@LievenDeFoor 

OEDT 9.3.2 added context-awareness, this should fix a lot of the false-positives.
